[build-system]
requires = [
    "setuptools >= 61",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
version = "0.6.6"
name = "panda3d-complexpbr"
authors = [
    {name = "Logan Bier"}
]
description = "IBL rendering module supporting real-time reflections and post-processing effects."
readme = "README.md"
keywords = ["nonengine","panda3d", "gamedev", "PBR", "IBL", "real-time", "simulation"]
license = "LicenseRef-Proprietary"
license-files = ["LICENSE","complexpbr/simplepbr_license.txt",]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "typing_extensions ~= 4.7",
]
requires-python = ">= 3.10"

[project.urls]
homepage = "https://github.com/rayanalysis/panda3d-complexpbr"

[tool.setuptools]
packages = ["complexpbr"]
